on: push

jobs:
  TestLin:
    name: TestLin
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Params
      id: buildParams
      run: |
          customParameters='"[
                        "-buildNumber", "${{ github.run_number }}",
                        "${{ matrix.customParameters }}",
                     ]"'

          customParameters=$(echo "$customParameters" | tr -d '\n')
          echo $customParameters
          echo "customParameters=$customParameters" >> "$GITHUB_OUTPUT"
        
    - name: Echo Params
      run: |
        echo ${{ steps.buildParams.outputs.customParameters }}
        echo ${{ join(fromJSON(steps.buildParams.outputs.customParameters), ' ') }}
