on: push

jobs:
  TestLin:
    name: TestLin
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run
      env:
        VARIABLE: >-
             ${{ 
                join(
                  fromJSON(
                      '[ 
                        "${{ github.run_number }}", 
                        "-buildNumber", "${{ github.run_number }}",
                        "-storefront", "asdf", 
                        "-buildEnvironment", "asdfa",
                        "-supabaseUrl", "asdf",
                        "-supabaseAnonKey", "asdfas",
                        "-gameAnalyticsGameKeyAndroid", "dfsdfasdfa",
                        "-gameAnalyticsSecretKeyAndroid", "aafdfsasdf",
                      ]'
                  ),
                ' ')
             }}
      run: |
        echo $VARIABLE
        
