on: push

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v6
      with:
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    
    - run: sudo du -a / | sort -n -r | head -n 10
