on: push

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
    - run: docker images
    
    - run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo docker rmi node:12 node:14 node:16 node:12-alpine node:14-alpine node:16-alpine moby/buildkit:latest debian:9 debian:10 debian:11 ubuntu:16.04 buildpack-deps:stretch buildpack-deps:buster buildpack-deps:bullseye
    
    - run: docker images -a
    
    - name: Maximize build space
      uses: easimon/maximize-build-space@v6
      with:
        overprovision-lvm: 'true'
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
    
    - run: sudo du -a / | sort -n -r | head -n 100
