on: push

jobs:
  Test:
    name: Test
    runs-on: macos-13
    
    steps:
    
    - run: |
        echo $PATH
        sudo cat /etc/paths
        ls /usr/local/lib/ruby/gems/3.0.0/bin
        bundle install
        ls /usr/local/lib/ruby/gems/3.0.0/bin
