on: push

jobs:
  Test:
    name: Test
    runs-on: windows-latest
    
    steps:
    - name: Disable Windows Defender
      run: Set-MpPreference -DisableRealtimeMonitoring $true
      
    - name: Check Windows defender
      run: Get-MpComputerStatus
