on: push

jobs:
  Test:
    name: Test
    runs-on: windows-latest
    
    steps:
    - name: Disable Windows Defender
      run: Uninstall-WindowsFeature Windows-Defender
      
    - name: Check Windows defender
      run: Get-MpComputerStatus
