on: push

jobs:
  TestLin:
    name: TestLin
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        whoami
        echo "::error ::Crazy Error"
        echo "::warning ::Crazy Warning"

  TestWin:
    name: TestWin
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        whoami
        echo "::error ::Crazy Error"
        echo "::warning ::Crazy Warning"

  TestMac:
    name: TestMac
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        whoami
        echo "::error ::Crazy Error"
        echo "::warning ::Crazy Warning"
