on: push

jobs:
  Test:
    name: Test
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        echo "::error ::Crazy Error"
        echo "::warning ::Crazy Warning"
